const building1 = require('./building.js')
console.log(building1.getName())
building1.setName('villa')
console.log(building1.getName())
const building2 = require ('./building.js')
console.log(building2.getName())